#!/bin/bash
# Prepare Armbian image with autoconfig for unattended first boot
#
# Usage: ./scripts/prepare-armbian-image.sh <image.img> [node_number]
#
# This script mounts an Armbian image and injects first-boot configuration
# to skip the interactive setup wizard.
#
# Reference: https://docs.armbian.com/User-Guide_Autoconfig/

set -e

# Configuration - Override via environment variables
ROOT_PASSWORD="${ROOT_PASSWORD:-Turing@Rk1#2024}"
SSH_PUBKEY_FILE="${SSH_PUBKEY_FILE:-$HOME/.ssh/workbench.pub}"
TIMEZONE="${TIMEZONE:-UTC}"
LOCALE="${LOCALE:-en_US.UTF-8}"
USER_SHELL="${USER_SHELL:-bash}"

# Node-specific static IPs
declare -A NODE_IPS=(
    [1]="10.10.88.73"
    [2]="10.10.88.74"
    [3]="10.10.88.75"
    [4]="10.10.88.76"
)
NETMASK="255.255.255.0"
GATEWAY="10.10.88.1"
DNS="10.10.88.1 8.8.8.8"

# Hostnames
declare -A NODE_HOSTNAMES=(
    [1]="turing-cp1"
    [2]="turing-w1"
    [3]="turing-w2"
    [4]="turing-w3"
)

usage() {
    echo "Usage: $0 <armbian-image.img> [node_number]"
    echo ""
    echo "Arguments:"
    echo "  armbian-image.img   Path to Armbian image file"
    echo "  node_number         Optional: 1-4 for static IP config"
    echo ""
    echo "Environment variables:"
    echo "  ROOT_PASSWORD       Root password (default: Turing@Rk1#2024)"
    echo "  SSH_PUBKEY_FILE     Path to SSH public key (default: ~/.ssh/workbench.pub)"
    echo "  TIMEZONE            Timezone (default: UTC)"
    echo "  LOCALE              Locale (default: en_US.UTF-8)"
    echo ""
    echo "Examples:"
    echo "  $0 Armbian.img                    # DHCP, inject SSH key"
    echo "  $0 Armbian.img 1                  # Static IP for node 1"
    echo "  ROOT_PASSWORD=secret $0 image.img # Custom password"
    exit 1
}

# Check arguments
if [[ $# -lt 1 ]]; then
    usage
fi

IMAGE="$1"
NODE_NUM="${2:-}"

if [[ ! -f "$IMAGE" ]]; then
    echo "Error: Image file not found: $IMAGE"
    exit 1
fi

# Check for root/sudo
if [[ $EUID -ne 0 ]]; then
    echo "This script requires root privileges to mount the image."
    echo "Re-running with sudo..."
    exec sudo "$0" "$@"
fi

# Create mount point
MOUNT_POINT=$(mktemp -d)
LOOP_DEVICE=""

cleanup() {
    echo "Cleaning up..."
    if [[ -n "$MOUNT_POINT" ]] && mountpoint -q "$MOUNT_POINT" 2>/dev/null; then
        umount "$MOUNT_POINT" || true
    fi
    if [[ -n "$LOOP_DEVICE" ]]; then
        losetup -d "$LOOP_DEVICE" 2>/dev/null || true
    fi
    rmdir "$MOUNT_POINT" 2>/dev/null || true
}
trap cleanup EXIT

echo "=== Preparing Armbian Image ==="
echo "Image: $IMAGE"
echo "Node: ${NODE_NUM:-all (DHCP)}"
echo ""

# Setup loop device with partition support
echo "Setting up loop device..."
LOOP_DEVICE=$(losetup -fP --show "$IMAGE")
echo "Loop device: $LOOP_DEVICE"

# Wait for partition to appear
sleep 1

# Find the root partition (usually partition 1 for Armbian)
ROOT_PART="${LOOP_DEVICE}p1"
if [[ ! -b "$ROOT_PART" ]]; then
    # Try partition 2 if 1 doesn't exist
    ROOT_PART="${LOOP_DEVICE}p2"
fi

if [[ ! -b "$ROOT_PART" ]]; then
    echo "Error: Could not find root partition"
    losetup -d "$LOOP_DEVICE"
    exit 1
fi

echo "Root partition: $ROOT_PART"

# Mount the root partition
echo "Mounting root partition..."
mount "$ROOT_PART" "$MOUNT_POINT"

# Read SSH public key if available
SSH_KEY=""
if [[ -f "$SSH_PUBKEY_FILE" ]]; then
    SSH_KEY=$(cat "$SSH_PUBKEY_FILE")
    echo "SSH key loaded from: $SSH_PUBKEY_FILE"
else
    echo "Warning: SSH public key not found at $SSH_PUBKEY_FILE"
fi

# Build autoconfig content
echo "Creating autoconfig file..."

AUTOCONFIG="# Armbian first-boot autoconfig
# Generated by prepare-armbian-image.sh
# Reference: https://docs.armbian.com/User-Guide_Autoconfig/

# Skip interactive prompts
PRESET_ROOT_PASSWORD=\"${ROOT_PASSWORD}\"
PRESET_USER_SHELL=\"${USER_SHELL}\"

# Skip user creation (we'll use root)
# Leave PRESET_USER_NAME empty to skip

# Locale and timezone
PRESET_LOCALE=\"${LOCALE}\"
PRESET_TIMEZONE=\"${TIMEZONE}\"
SET_LANG_BASED_ON_LOCATION=\"0\"
"

# Add static IP config if node number provided
if [[ -n "$NODE_NUM" ]] && [[ -n "${NODE_IPS[$NODE_NUM]}" ]]; then
    STATIC_IP="${NODE_IPS[$NODE_NUM]}"
    HOSTNAME="${NODE_HOSTNAMES[$NODE_NUM]}"

    AUTOCONFIG+="
# Static network configuration for node $NODE_NUM
PRESET_NET_CHANGE_DEFAULTS=\"1\"
PRESET_NET_USE_STATIC=\"1\"
PRESET_NET_STATIC_IP=\"${STATIC_IP}\"
PRESET_NET_STATIC_MASK=\"${NETMASK}\"
PRESET_NET_STATIC_GATEWAY=\"${GATEWAY}\"
PRESET_NET_STATIC_DNS=\"${DNS}\"
"
    echo "Static IP configured: $STATIC_IP ($HOSTNAME)"
else
    echo "Using DHCP for network configuration"
fi

# Write autoconfig file
echo "$AUTOCONFIG" > "$MOUNT_POINT/root/.not_logged_in_yet"
chmod 644 "$MOUNT_POINT/root/.not_logged_in_yet"

# Create provisioning script for additional setup
PROVISION_SCRIPT="#!/bin/bash
# Post-firstboot provisioning script
# This runs once after first login

set -e

# Set hostname if node number was specified
HOSTNAME=\"${NODE_HOSTNAMES[$NODE_NUM]:-}\"
if [[ -n \"\$HOSTNAME\" ]]; then
    hostnamectl set-hostname \"\$HOSTNAME\"
    echo \"\$HOSTNAME\" > /etc/hostname
fi

# Add SSH authorized key
if [[ -n \"$SSH_KEY\" ]]; then
    mkdir -p /root/.ssh
    chmod 700 /root/.ssh
    echo \"$SSH_KEY\" >> /root/.ssh/authorized_keys
    chmod 600 /root/.ssh/authorized_keys
    echo \"SSH key added to authorized_keys\"
fi

# Update /etc/hosts with cluster nodes
cat >> /etc/hosts << 'HOSTS'

# Turing Pi RK1 Cluster
10.10.88.70  turing-bmc
10.10.88.73  turing-cp1
10.10.88.74  turing-w1
10.10.88.75  turing-w2
10.10.88.76  turing-w3
HOSTS

# Disable password authentication for SSH (key-only)
# Uncomment if you want key-only auth:
# sed -i 's/^#*PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config
# systemctl restart sshd

echo \"Provisioning complete!\"
"

echo "$PROVISION_SCRIPT" > "$MOUNT_POINT/root/provisioning.sh"
chmod 755 "$MOUNT_POINT/root/provisioning.sh"

# Show what was created
echo ""
echo "=== Autoconfig file created ==="
cat "$MOUNT_POINT/root/.not_logged_in_yet"
echo ""
echo "=== Provisioning script created ==="
echo "Location: /root/provisioning.sh"
echo ""

# Sync and unmount
echo "Syncing and unmounting..."
sync
umount "$MOUNT_POINT"
losetup -d "$LOOP_DEVICE"
LOOP_DEVICE=""

echo ""
echo "=== Image prepared successfully ==="
echo ""
echo "Flash with:"
echo "  tpi flash --node ${NODE_NUM:-1} --image-path $IMAGE"
echo ""
echo "The node will boot directly to a root shell with:"
echo "  - Root password: ${ROOT_PASSWORD}"
echo "  - SSH key: ${SSH_PUBKEY_FILE:-none}"
if [[ -n "$NODE_NUM" ]]; then
    echo "  - Static IP: ${NODE_IPS[$NODE_NUM]}"
    echo "  - Hostname: ${NODE_HOSTNAMES[$NODE_NUM]}"
fi
